# Generated by Django 5.0.2 on 2024-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.BigIntegerField(unique=True)),
                ('page_title', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(verbose_name='revision date')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_tags', models.ManyToManyField(related_name='events', to='pages.eventtag')),
            ],
        ),
    ]
